### ISSUE TITLE
Overlapping recipe

### ISSUE THREAD

**Issue by PotatoBlade197** [ZsoltMolnarrr/Runes#11]
Im trying to use create to make diorite where the recipe is cobblestone and quartz (the same as lightning rune) and it keeps making lighting rune instead of diorite like i need it to be. there's no filter for mechanical crafters in create so i cant just tell it to make diorite

**Comment by PotatoBlade197** [comment]
sorry, i mean make diorite from cobblestone and quartz, not andesite. brain died when i wrote the issue

**Comment by ZsoltMolnarrr** [comment]
Hello,

I am sorry to tell you that the content mod you are using in addition to Runes is causing the problem.
Runes mod does not contain such recipe.
